### ISSUE TITLE
Spring Boot 2.0 Compatibility

### ISSUE THREAD

**Issue by bentrility** [zalando/spring-cloud-config-aws-kms#33]
Any chance you can share when you think this will be ready for spring boot 2.0?

Thanks again for your work. Happy to help.

**Comment by bentrility** [comment]
Yes, I've been working on updating one of our repositories, and am running into:

```
java.lang.NoSuchMethodError: org.springframework.boot.builder.SpringApplicationBuilder.<init>([Ljava/lang/Object;)V
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:157)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:98)
```

It looks like the underlying issue is that spring-cloud-config is not yet compatible with spring boot 2, which it appears they are working on with their [Finchley release](http://projects.spring.io/spring-cloud/#release-trains).

They've also got an issue for the [error I'm seeing](https://github.com/spring-cloud/spring-cloud-config/issues/836), but it looks like it's closed because they aren't boot 2 compatible yet.

**Comment by harti2006** [comment]
I fear I won't be able to look deeply into the issue this week. Contributions are welcome, otherwise I'll get back to you, when I have the fix ready.

**Comment by bentrility** [comment]
I don't know that either of us can do anything (or should), until an official release is cut for Finchley.

**Comment by nagarajapalla** [comment]
Spring Cloud Finchley builds on Spring Boot 2.0.x and is not compatible with 1.x.y.
Finchley is in RC1 as of 2018-04-24. waiting for official release

**Comment by harti2006** [comment]
@bentrility @nagarajapalla I created a separate branch to update this library to Spring Cloud Finchley RC1: https://github.com/zalando/spring-cloud-config-aws-kms/tree/spring-boot-2.0
Do you maybe have the chance to try this out locally?

**Comment by harti2006** [comment]
I released version 3.0 of this library, which builds upon the Spring Cloud Finchley release train.

**Comment by benkiefer** [comment]
Thanks @harti2006. I upgraded today, and things are looking good.
